export const cryptocurrencies = [
    {
        id: "bitcoin",
        symbol: "BTC",
        name: "Bitcoin",
        logo:"/static/images/crypto/bitcoin.png",
    },
    {
        id: "ethereum",
        symbol: "ETH",
        name: "Ethereum",
        logo:"/static/images/crypto/ethereum.png",
    },
    {
        id: "matic-network",
        symbol: "MATIC",
        name: "Polygon",
        logo:"/static/images/crypto/matic-network.png",
    },
    {
        id: "binancecoin",
        symbol: "BNB",
        name: "BNB",
        logo:"/static/images/crypto/binancecoin.png",
    },
    {
        id: "tether",
        symbol: "USDT",
        name: "Tether",
        logo:"/static/images/crypto/tether.png",
    },
    {
        id: "usd-coin",
        symbol: "USDC",
        name: "USD Coin",
        logo:"/static/images/crypto/usd-coin.png",
    },
    {
        id: "binance-usd",
        symbol: "BUSD",
        name: "Binance USD",
        logo:"/static/images/crypto/binance-usd.png",
    },
    {
        id: "dai",
        symbol: "DAI",
        name: "Dai",
        logo:"/static/images/crypto/dai.png",
    },
    {
        id: "ripple",
        symbol: "XRP",
        name: "XRP (Ripple)",
        logo:"/static/images/crypto/ripple.png",
    },
    {
        id: "cardano",
        symbol: "ADA",
        name: "Cardano",
        logo:"/static/images/crypto/cardano.png",
    },
    {
        id: "dogecoin",
        symbol: "DOGE",
        name: "Dogecoin",
        logo:"/static/images/crypto/dogecoin.png",
    },
    {
        id: "solana",
        symbol: "SOL",
        name: "Solana",
        logo:"/static/images/crypto/solana.png",
    },
    {
        id: "polkadot",
        symbol: "DOT",
        name: "Polkadot",
        logo:"/static/images/crypto/polkadot.png",
    },
    {
        id: "shiba-inu",
        symbol: "SHIB",
        name: "Shiba Inu",
        logo:"/static/images/crypto/shiba-inu.png",
    },
    {
        id: "avalanche-2",
        symbol: "AVAX",
        name: "Avalanche",
        logo:"/static/images/crypto/avalanche-2.png",
    },
    {
        id: "uniswap",
        symbol: "UNI",
        name: "Uniswap",
        logo:"/static/images/crypto/uniswap.png",
    },
    {
        id: "tron",
        symbol: "TRX",
        name: "TRON",
        logo:"/static/images/crypto/tron.png",
    },
    {
        id: "wrapped-bitcoin",
        symbol: "WBTC",
        name: "Wrapped Bitcoin",
        logo:"/static/images/crypto/wrapped-bitcoin.png",
    },
    {
        id: "litecoin",
        symbol: "LTC",
        name: "Litecoin",
        logo:"/static/images/crypto/litecoin.png",
    },
    {
        id: "chainlink",
        symbol: "LINK",
        name: "Chainlink",
        logo:"/static/images/crypto/chainlink.png",
    },
    {
        id: "ethereum-classic",
        symbol: "ETC",
        name: "Ethereum Classic",
        logo:"/static/images/crypto/ethereum-classic.png",
    },
    {
        id: "monero",
        symbol: "XMR",
        name: "Monero",
        logo:"/static/images/crypto/monero.png",
    },
    {
        id: "bitcoin-cash",
        symbol: "BCH",
        name: "Bitcoin Cash",
        logo:"/static/images/crypto/bitcoin-cash.png",
    },
    {
        id: "vechain",
        symbol: "VET",
        name: "Vechain",
        logo:"/static/images/crypto/vechain.png",
    },
    {
        id: "stellar",
        symbol: "XML",
        name: "Stellar",
        logo:"/static/images/crypto/stellar.png",
    },
    {
        id: "tezos",
        symbol: "XZT",
        name: "Tezos",
        logo:"/static/images/crypto/tezos.png",
    },
    {
        id: "axie-infinity",
        symbol: "AXS",
        name: "Axie Infinity",
        logo:"/static/images/crypto/axie-infinity.png",
    },
    {
        id: "decentraland",
        symbol: "MANA",
        name: "Decentraland",
        logo:"/static/images/crypto/decentraland.png",
    },
    {
        id: "the-sandbox",
        symbol: "Sand",
        name: "The Sandbox",
        logo:"/static/images/crypto/the-sandbox.png",
    },
    {
        id: "apecoin",
        symbol: "APE",
        name: "ApeCoin",
        logo:"/static/images/crypto/apecoin.png",
    },
    {
        id: "near",
        symbol: "NEAR",
        name: "NEAR Protocol",
        logo:"/static/images/crypto/near.png",
    },
    {
        id: "internet-computer",
        symbol: "ICP",
        name: "Interner Computer",
        logo:"/static/images/crypto/internet-computer.png",
    },
    {
        id: "aave",
        symbol: "AAVE",
        name: "Aave",
        logo:"/static/images/crypto/aave.png",
    },
    {
        id: "huobi-token",
        symbol: "HT",
        name: "Huobi",
        logo:"/static/images/crypto/huobi-token.png",
    },
    {
        id: "kucoin-shares",
        symbol: "KCS",
        name: "Kucoin",
        logo:"/static/images/crypto/kucoin-shares.png",
    },
    {
        id: "ethereum-name-service",
        symbol: "ENS",
        name: "Ethereum Name Service",
        logo:"/static/images/crypto/ethereum-name-service.png",
    },
];
